version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: "386"
    ldflags:
      - -s -w -X github.com/ygrebnov/links/internal.version={{.Version}} -X github.com/ygrebnov/links/internal.buildTime={{.Date}}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
    wrap_in_directory: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^vendor:"
      - "^tests:"

brews:
  - repository:
      owner: ygrebnov
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    goarm: "7"
    commit_author:
      name: ygrebnov
      email: grebnov@gmail.com
    homepage: "https://github.com/ygrebnov/links"
    description: "A Go-based tool for checking pages links statuses at the given host."
    license: "Apache License 2.0"
    skip_upload: auto